version: '3'

services:
  rss-proxy-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    environment:
      - REDIS_HOST=redis
      - TZ=Asia/Jerusalem

  redis:
    image: "redis:latest"
